"""
Simple FlowTTS client.

- Opens a single WebSocket connection for a given ``call_id``.
- Sends one or more ``synthesize`` requests (can be treated as a stream of prompts).
- Writes each returned audio message to a separate WAV file.
"""

import asyncio
import base64
import json
import time
import uuid
from pathlib import Path
from typing import Iterable

import websockets


WS_URL = "ws://localhost:8765/ws"


async def synthesize_stream(texts: Iterable[str], call_id: str) -> None:
    """Send multiple synthesize requests over a single WebSocket connection.

    This simulates a streaming text scenario: same call_id, multiple text_ids.
    """
    url = f"{WS_URL}/{call_id}"
    async with websockets.connect(url) as ws:
        print(f"[{time.time():.3f}] Connected to {url}")

        for text in texts:
            text_id = str(uuid.uuid4())
            payload = {
                "type": "synthesize",
                "call_id": call_id,
                "text_id": text_id,
                "text": text,
            }
            send_ts = time.time()
            await ws.send(json.dumps(payload))
            print(f"[{send_ts:.3f}] Sent text_id={text_id}")

            raw = await ws.recv()
            recv_ts = time.time()
            msg = json.loads(raw)

            if msg.get("type") == "error":
                raise RuntimeError(msg.get("error", "Unknown error"))

            if msg.get("type") != "audio":
                raise RuntimeError(f"Unexpected message type: {msg.get('type')}")

            audio_b64 = msg["audio_base64"]
            audio_bytes = base64.b64decode(audio_b64)

            out_path = Path(f"flowtts_{call_id}_{text_id}.wav")
            out_path.write_bytes(audio_bytes)
            print(
                f"[{recv_ts:.3f}] Received audio for text_id={text_id} "
                f"(latency={recv_ts - send_ts:.3f}s) → {out_path}"
            )


async def main() -> None:
    call_id = str(uuid.uuid4())
    texts = [
        "नमस्ते, आप कैसे हैं?",
        "This is a sample sentence generated by FlowTTS.",
        "Here is another sentence to simulate streaming text over the same call.",
    ]
    await synthesize_stream(texts, call_id)


if __name__ == "__main__":
    asyncio.run(main())
