"""Pipeline position: SETUP — generate a Triton Inference Server model repository.

    python -m flowtts.dhvaani.setup.build_triton_repo --out triton/model_repository

Relationship to upstream
------------------------
This follows the structure of `runtime/nvidia_triton/` in k2-fsa/ZipVoice: one
Python-backend model that owns the whole pipeline, with Triton's dynamic batcher
in front of it and a TensorRT engine underneath the flow decoder.

Two differences, both deliberate:

  * Upstream's `model.py` calls `ZipVoice.sample()` per batch, so every request
    in a Triton batch runs the same number of ODE steps in lockstep and the
    batch finishes only when its slowest member does. This model wraps
    `DhvaaniEngine` instead, so requests are additionally continuous-batched
    INSIDE the model across Triton batches: a request that arrives while another
    is on step 6 joins at step 0 in the same forward pass.
  * Voices resolve from the persistent voice store by `voice_id`, so the
    reference waveform is not shipped on every request. Passing `reference_wav`
    + `reference_text` inline still works, for parity with upstream's client.

When to use Triton instead of the in-process server
---------------------------------------------------
Triton is right when the GPU is shared with other models, or when you need its
model repository, versioning, health and metrics plane. If DhVaani owns the box,
`python -m flowtts.dhvaani.server --backend trt` is strictly lower latency: it
removes an IPC hop per request and streams straight out of the engine.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from flowtts.dhvaani.config import dhv_settings

CONFIG_PBTXT = """# Generated by flowtts.dhvaani.setup.build_triton_repo -- do not edit by hand.
name: "dhvaani"
backend: "python"
max_batch_size: {max_batch}

# Triton batches whole REQUESTS here. The engine inside additionally
# continuous-batches at the ODE-step level, so this queue delay only has to be
# long enough to coalesce near-simultaneous arrivals, not to fill a batch.
dynamic_batching {{
  preferred_batch_size: [ {pref1}, {pref2} ]
  max_queue_delay_microseconds: {queue_delay}
}}

# Streaming: responses are sent as spans finish rather than all at the end.
model_transaction_policy {{
  decoupled: {decoupled}
}}

parameters [
  {{ key: "profile",            value: {{ string_value: "{profile}" }} }},
  {{ key: "backend_kind",       value: {{ string_value: "{backend_kind}" }} }},
  {{ key: "trt_engine_dir",     value: {{ string_value: "{trt_engine_dir}" }} }},
  {{ key: "voices_dir",         value: {{ string_value: "{voices_dir}" }} }},
  {{ key: "model_dir",          value: {{ string_value: "{model_dir}" }} }},
  {{ key: "output_sample_rate", value: {{ string_value: "{sample_rate}" }} }}
]

input [
  {{ name: "target_text",       data_type: TYPE_STRING, dims: [1] }},
  {{ name: "voice_id",          data_type: TYPE_STRING, dims: [1], optional: true }},
  {{ name: "language",          data_type: TYPE_STRING, dims: [1], optional: true }},
  {{ name: "reference_wav",     data_type: TYPE_FP32,   dims: [-1], optional: true }},
  {{ name: "reference_wav_len", data_type: TYPE_INT32,  dims: [1],  optional: true }},
  {{ name: "reference_text",    data_type: TYPE_STRING, dims: [1],  optional: true }}
]

output [
  {{ name: "waveform",    data_type: TYPE_FP32,  dims: [-1] }},
  {{ name: "sample_rate", data_type: TYPE_INT32, dims: [1] }}
]

instance_group [
  {{ count: {instances}, kind: KIND_GPU }}
]
"""

MODEL_PY = '''# Generated by flowtts.dhvaani.setup.build_triton_repo.
# Triton Python backend model wrapping DhvaaniEngine.
import asyncio
import io
import json
import threading

import numpy as np
import triton_python_backend_utils as pb_utils


class TritonPythonModel:
    def initialize(self, args):
        cfg = json.loads(args["model_config"])
        params = {k: v["string_value"] for k, v in cfg.get("parameters", {}).items()}
        self.decoupled = bool(
            cfg.get("model_transaction_policy", {}).get("decoupled", False)
        )

        from flowtts.dhvaani.config import apply_profile, dhv_settings

        s = dhv_settings
        if params.get("profile"):
            apply_profile(s, params["profile"])
        if params.get("backend_kind"):
            s.backend.kind = params["backend_kind"]
        if params.get("trt_engine_dir"):
            s.backend.trt_engine_dir = params["trt_engine_dir"]
        if params.get("voices_dir"):
            s.voice.store_dir = params["voices_dir"]
        if params.get("model_dir"):
            s.model.local_dir = params["model_dir"]
        if params.get("output_sample_rate"):
            s.audio.output_sample_rate = int(params["output_sample_rate"])
        self.sample_rate = s.audio.output_sample_rate

        # The engine is asyncio-native and owns a long-lived scheduler task, but
        # Triton's Python backend gives us no event loop. Run a private loop on
        # a background thread and dispatch to it with run_coroutine_threadsafe.
        self._loop = asyncio.new_event_loop()
        self._thread = threading.Thread(target=self._loop.run_forever, daemon=True)
        self._thread.start()

        from flowtts.dhvaani.engine.engine import DhvaaniEngine

        self.engine = DhvaaniEngine(s)
        asyncio.run_coroutine_threadsafe(self.engine.start(), self._loop).result()
        pb_utils.Logger.log_info("dhvaani: engine ready")

    # -- helpers ---------------------------------------------------------
    @staticmethod
    def _text(request, name):
        t = pb_utils.get_input_tensor_by_name(request, name)
        if t is None:
            return None
        arr = t.as_numpy()
        if arr.size == 0:
            return None
        v = arr.reshape(-1)[0]
        return v.decode("utf-8") if isinstance(v, (bytes, bytearray)) else str(v)

    def _ensure_voice(self, request, voice_id):
        """Register an inline reference clip as a voice, for upstream-client parity."""
        if voice_id and self.engine.voices.exists(voice_id):
            return voice_id
        wav_t = pb_utils.get_input_tensor_by_name(request, "reference_wav")
        ref_text = self._text(request, "reference_text")
        if wav_t is None or not ref_text:
            return voice_id
        wav = wav_t.as_numpy().reshape(-1).astype(np.float32)
        len_t = pb_utils.get_input_tensor_by_name(request, "reference_wav_len")
        if len_t is not None:
            wav = wav[: int(len_t.as_numpy().reshape(-1)[0])]

        import soundfile as sf

        buf = io.BytesIO()
        sf.write(buf, wav, 24000, format="WAV", subtype="PCM_16")
        vid = voice_id or ("inline_" + str(abs(hash(ref_text)) % (10 ** 10)))
        self.engine.voices.create(
            voice_id=vid,
            audio=buf.getvalue(),
            transcript=ref_text,
            language="",
            overwrite=True,
            source_filename="triton-inline",
        )
        return vid

    def _tensors(self, pcm_bytes, sample_rate):
        pcm = np.frombuffer(pcm_bytes, dtype=np.int16).astype(np.float32) / 32768.0
        return [
            pb_utils.Tensor("waveform", pcm),
            pb_utils.Tensor("sample_rate", np.array([sample_rate], dtype=np.int32)),
        ]

    def _stream(self, text, voice_id, language, sender):
        async def _run():
            try:
                async for chunk in self.engine.synthesize_stream(text, voice_id, language):
                    if not chunk.audio:
                        continue
                    sender.send(
                        pb_utils.InferenceResponse(
                            output_tensors=self._tensors(chunk.audio, chunk.sample_rate)
                        )
                    )
            except Exception as e:
                sender.send(pb_utils.InferenceResponse(error=pb_utils.TritonError(str(e))))
            finally:
                sender.send(flags=pb_utils.TRITONSERVER_RESPONSE_COMPLETE_FINAL)

        asyncio.run_coroutine_threadsafe(_run(), self._loop)

    # -- execute ---------------------------------------------------------
    def execute(self, requests):
        if self.decoupled:
            for request in requests:
                text = self._text(request, "target_text") or ""
                vid = self._ensure_voice(request, self._text(request, "voice_id"))
                lang = self._text(request, "language")
                self._stream(text, vid, lang, request.get_response_sender())
            return None

        responses = []
        for request in requests:
            try:
                text = self._text(request, "target_text") or ""
                vid = self._ensure_voice(request, self._text(request, "voice_id"))
                lang = self._text(request, "language")
                coro = self.engine.synthesize(text, vid, lang)
                pcm_bytes, _metrics = asyncio.run_coroutine_threadsafe(
                    coro, self._loop
                ).result()
                responses.append(
                    pb_utils.InferenceResponse(
                        output_tensors=self._tensors(pcm_bytes, self.sample_rate)
                    )
                )
            except Exception as e:
                responses.append(
                    pb_utils.InferenceResponse(error=pb_utils.TritonError(str(e)))
                )
        return responses

    def finalize(self):
        try:
            asyncio.run_coroutine_threadsafe(self.engine.stop(), self._loop).result(timeout=10)
        except Exception:
            pass
        self._loop.call_soon_threadsafe(self._loop.stop)
'''

README = """# DhVaani on NVIDIA Triton Inference Server

Generated by `python -m flowtts.dhvaani.setup.build_triton_repo`.

## When to use this

Use Triton when the GPU is **shared** with other models, or when you need its
model repository, versioning, health and metrics plane.

If DhVaani owns the box, the in-process server is faster:

    python -m flowtts.dhvaani.server --backend trt --ports 4 --http-port 8000

It removes an IPC hop per request and streams straight out of the engine.

## Prerequisites

1. Fetch the model (gated -- accept the terms on the Hub first):

       export HF_TOKEN=hf_...
       python -m flowtts.dhvaani.setup.fetch_model

2. Build TensorRT engines (optional but recommended):

       python -m flowtts.dhvaani.setup.build_trt --max-batch 128

3. Create at least one voice, via the REST API of a local server or by pointing
   `voices_dir` at an existing store.

## Run

    docker run --rm --gpus all --net host --shm-size 2g \\
      -v $PWD:/workspace -w /workspace -e PYTHONPATH=/workspace \\
      nvcr.io/nvidia/tritonserver:24.12-py3 \\
      tritonserver --model-repository=/workspace/triton/model_repository

The Python backend needs FlowTTS and its dependencies importable inside the
container -- either bake them into an image or mount a prepared venv.

## Query

    import numpy as np, tritonclient.grpc as tc
    c = tc.InferenceServerClient("localhost:8001")
    text = tc.InferInput("target_text", [1, 1], "BYTES")
    text.set_data_from_numpy(np.array([["namaste".encode()]], dtype=object))
    vid = tc.InferInput("voice_id", [1, 1], "BYTES")
    vid.set_data_from_numpy(np.array([[b"simran"]], dtype=object))
    r = c.infer("dhvaani", [text, vid])
    wav = r.as_numpy("waveform")

With `decoupled: true` (the default) use `stream_infer` and read the responses
as they arrive; each one is a finished span.

## Batching notes

`max_batch_size` and `max_queue_delay_microseconds` control how Triton groups
*requests*. Inside the model, `DhvaaniEngine` additionally continuous-batches at
the ODE-step level, so the queue delay only needs to coalesce near-simultaneous
arrivals -- 300-500 us is plenty. Raising it further buys nothing and costs
time-to-first-byte directly.
"""


def generate(out_dir: Path, settings=None, instances: int = 1,
             decoupled: bool = True, profile: str = "balanced") -> Path:
    s = settings or dhv_settings
    model_dir = out_dir / "dhvaani"
    (model_dir / "1").mkdir(parents=True, exist_ok=True)

    max_batch = min(s.engine.max_batch_size, 64)
    cfg = CONFIG_PBTXT.format(
        max_batch=max_batch,
        pref1=max(1, max_batch // 4),
        pref2=max(2, max_batch // 2),
        queue_delay=400,
        decoupled="true" if decoupled else "false",
        profile=profile,
        backend_kind=s.backend.kind,
        trt_engine_dir=s.backend.trt_engine_dir,
        voices_dir=s.voice.store_dir,
        model_dir=s.model.local_dir or "",
        sample_rate=s.audio.output_sample_rate,
        instances=instances,
    )
    (model_dir / "config.pbtxt").write_text(cfg)
    (model_dir / "1" / "model.py").write_text(MODEL_PY)
    (out_dir.parent / "README.md").write_text(README)
    return model_dir


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a Triton model repository")
    ap.add_argument("--out", default="triton/model_repository")
    ap.add_argument("--instances", type=int, default=1)
    ap.add_argument("--profile", default="balanced",
                    choices=["fast", "balanced", "quality"])
    ap.add_argument("--no-decoupled", action="store_true",
                    help="Disable streaming responses (simpler clients)")
    ap.add_argument("--clean", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    if args.clean and out.exists():
        shutil.rmtree(out)
    d = generate(out, dhv_settings, args.instances,
                 decoupled=not args.no_decoupled, profile=args.profile)
    print(f"Wrote {d}/config.pbtxt and {d}/1/model.py")
    print(f"See {out.parent / 'README.md'} for how to run it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
