# Generated by flowtts.dhvaani.setup.build_triton_repo.
# Triton Python backend model wrapping DhvaaniEngine.
import asyncio
import io
import json
import threading

import numpy as np
import triton_python_backend_utils as pb_utils


class TritonPythonModel:
    def initialize(self, args):
        cfg = json.loads(args["model_config"])
        params = {k: v["string_value"] for k, v in cfg.get("parameters", {}).items()}
        self.decoupled = bool(
            cfg.get("model_transaction_policy", {}).get("decoupled", False)
        )

        from flowtts.dhvaani.config import apply_profile, dhv_settings

        s = dhv_settings
        if params.get("profile"):
            apply_profile(s, params["profile"])
        if params.get("backend_kind"):
            s.backend.kind = params["backend_kind"]
        if params.get("trt_engine_dir"):
            s.backend.trt_engine_dir = params["trt_engine_dir"]
        if params.get("voices_dir"):
            s.voice.store_dir = params["voices_dir"]
        if params.get("model_dir"):
            s.model.local_dir = params["model_dir"]
        if params.get("output_sample_rate"):
            s.audio.output_sample_rate = int(params["output_sample_rate"])
        self.sample_rate = s.audio.output_sample_rate

        # The engine is asyncio-native and owns a long-lived scheduler task, but
        # Triton's Python backend gives us no event loop. Run a private loop on
        # a background thread and dispatch to it with run_coroutine_threadsafe.
        self._loop = asyncio.new_event_loop()
        self._thread = threading.Thread(target=self._loop.run_forever, daemon=True)
        self._thread.start()

        from flowtts.dhvaani.engine.engine import DhvaaniEngine

        self.engine = DhvaaniEngine(s)
        asyncio.run_coroutine_threadsafe(self.engine.start(), self._loop).result()
        pb_utils.Logger.log_info("dhvaani: engine ready")

    # -- helpers ---------------------------------------------------------
    @staticmethod
    def _text(request, name):
        t = pb_utils.get_input_tensor_by_name(request, name)
        if t is None:
            return None
        arr = t.as_numpy()
        if arr.size == 0:
            return None
        v = arr.reshape(-1)[0]
        return v.decode("utf-8") if isinstance(v, (bytes, bytearray)) else str(v)

    def _ensure_voice(self, request, voice_id):
        """Register an inline reference clip as a voice, for upstream-client parity."""
        if voice_id and self.engine.voices.exists(voice_id):
            return voice_id
        wav_t = pb_utils.get_input_tensor_by_name(request, "reference_wav")
        ref_text = self._text(request, "reference_text")
        if wav_t is None or not ref_text:
            return voice_id
        wav = wav_t.as_numpy().reshape(-1).astype(np.float32)
        len_t = pb_utils.get_input_tensor_by_name(request, "reference_wav_len")
        if len_t is not None:
            wav = wav[: int(len_t.as_numpy().reshape(-1)[0])]

        import soundfile as sf

        buf = io.BytesIO()
        sf.write(buf, wav, 24000, format="WAV", subtype="PCM_16")
        vid = voice_id or ("inline_" + str(abs(hash(ref_text)) % (10 ** 10)))
        self.engine.voices.create(
            voice_id=vid,
            audio=buf.getvalue(),
            transcript=ref_text,
            language="",
            overwrite=True,
            source_filename="triton-inline",
        )
        return vid

    def _tensors(self, pcm_bytes, sample_rate):
        pcm = np.frombuffer(pcm_bytes, dtype=np.int16).astype(np.float32) / 32768.0
        return [
            pb_utils.Tensor("waveform", pcm),
            pb_utils.Tensor("sample_rate", np.array([sample_rate], dtype=np.int32)),
        ]

    def _stream(self, text, voice_id, language, sender):
        async def _run():
            try:
                async for chunk in self.engine.synthesize_stream(text, voice_id, language):
                    if not chunk.audio:
                        continue
                    sender.send(
                        pb_utils.InferenceResponse(
                            output_tensors=self._tensors(chunk.audio, chunk.sample_rate)
                        )
                    )
            except Exception as e:
                sender.send(pb_utils.InferenceResponse(error=pb_utils.TritonError(str(e))))
            finally:
                sender.send(flags=pb_utils.TRITONSERVER_RESPONSE_COMPLETE_FINAL)

        asyncio.run_coroutine_threadsafe(_run(), self._loop)

    # -- execute ---------------------------------------------------------
    def execute(self, requests):
        if self.decoupled:
            for request in requests:
                text = self._text(request, "target_text") or ""
                vid = self._ensure_voice(request, self._text(request, "voice_id"))
                lang = self._text(request, "language")
                self._stream(text, vid, lang, request.get_response_sender())
            return None

        responses = []
        for request in requests:
            try:
                text = self._text(request, "target_text") or ""
                vid = self._ensure_voice(request, self._text(request, "voice_id"))
                lang = self._text(request, "language")
                coro = self.engine.synthesize(text, vid, lang)
                pcm_bytes, _metrics = asyncio.run_coroutine_threadsafe(
                    coro, self._loop
                ).result()
                responses.append(
                    pb_utils.InferenceResponse(
                        output_tensors=self._tensors(pcm_bytes, self.sample_rate)
                    )
                )
            except Exception as e:
                responses.append(
                    pb_utils.InferenceResponse(error=pb_utils.TritonError(str(e)))
                )
        return responses

    def finalize(self):
        try:
            asyncio.run_coroutine_threadsafe(self.engine.stop(), self._loop).result(timeout=10)
        except Exception:
            pass
        self._loop.call_soon_threadsafe(self._loop.stop)
